[workspace]

members = [
    "two-sum",
    "add-two-numbers", # 2
    "minimum-swaps-to-make-sequences-increasing", # 801
    "linked-list-components", # 817
    "score-of-parentheses", # 856
    "check-if-one-string-swap-can-make-strings-equal", # 1790
]